const negaraData = [
  { negara: "Afganistan", ibukota: "Kabul", level: "Sedang" },
  { negara: "Afrika Selatan", ibukota: "Pretoria", level: "Sedang" },
  { negara: "Albania", ibukota: "Tirana", level: "Sulit" },
  { negara: "Aljazair", ibukota: "Aljir", level: "Sedang" },
  { negara: "Amerika Serikat", ibukota: "Washington D.C.", level: "Mudah" },
  { negara: "Andorra", ibukota: "Andorra la Vella", level: "Sulit" },
  { negara: "Angola", ibukota: "Luanda", level: "Sulit" },
  { negara: "Antigua dan Barbuda", ibukota: "Saint John's", level: "Sulit" },
  { negara: "Arab Saudi", ibukota: "Riyadh", level: "Sedang" },
  { negara: "Argentina", ibukota: "Buenos Aires", level: "Sedang" },
  { negara: "Armenia", ibukota: "Yerevan", level: "Sulit" },
  { negara: "Australia", ibukota: "Canberra", level: "Mudah" },
  { negara: "Austria", ibukota: "Wina", level: "Sedang" },
  { negara: "Azerbaijan", ibukota: "Baku", level: "Sedang" },
  { negara: "Bahama", ibukota: "Nassau", level: "Sulit" },
  { negara: "Bahrain", ibukota: "Manama", level: "Sedang" },
  { negara: "Bangladesh", ibukota: "Dhaka", level: "Sedang" },
  { negara: "Barbados", ibukota: "Bridgetown", level: "Sulit" },
  { negara: "Belanda", ibukota: "Amsterdam", level: "Sedang" },
  { negara: "Belarus", ibukota: "Minsk", level: "Sedang" },
  { negara: "Belgia", ibukota: "Brussels", level: "Sedang" },
  { negara: "Belize", ibukota: "Belmopan", level: "Sulit" },
  { negara: "Benin", ibukota: "Porto-Novo", level: "Sulit" },
  { negara: "Bhutan", ibukota: "Thimphu", level: "Sulit" },
  { negara: "Bolivia", ibukota: "Sucre", level: "Sulit" },
  { negara: "Bosnia dan Herzegovina", ibukota: "Sarajevo", level: "Sulit" },
  { negara: "Botswana", ibukota: "Gaborone", level: "Sulit" },
  { negara: "Brasil", ibukota: "Brasilia", level: "Mudah" },
  { negara: "Britania Raya", ibukota: "London", level: "Mudah" },
  { negara: "Brunei", ibukota: "Bandar Seri Begawan", level: "Sulit" },
  { negara: "Bulgaria", ibukota: "Sofia", level: "Sedang" },
  { negara: "Burkina Faso", ibukota: "Ouagadougou", level: "Sulit" },
  { negara: "Burundi", ibukota: "Gitega", level: "Sulit" },
  { negara: "Chad", ibukota: "N'Djamena", level: "Sulit" },
  { negara: "Chili", ibukota: "Santiago", level: "Sedang" },
  { negara: "Cina", ibukota: "Beijing", level: "Mudah" },
  { negara: "Denmark", ibukota: "Kopenhagen", level: "Sedang" },
  { negara: "Djibouti", ibukota: "Djibouti", level: "Sulit" },
  { negara: "Dominika", ibukota: "Roseau", level: "Sulit" },
  { negara: "Ekuador", ibukota: "Quito", level: "Sedang" },
  { negara: "El Salvador", ibukota: "San Salvador", level: "Sedang" },
  { negara: "Eritrea", ibukota: "Asmara", level: "Sulit" },
  { negara: "Estonia", ibukota: "Tallinn", level: "Sedang" },
  { negara: "Eswatini", ibukota: "Mbabane", level: "Sulit" },
  { negara: "Ethiopia", ibukota: "Addis Ababa", level: "Sulit" },
  { negara: "Fiji", ibukota: "Suva", level: "Sulit" },
  { negara: "Filipina", ibukota: "Manila", level: "Sedang" },
  { negara: "Finlandia", ibukota: "Helsinki", level: "Sedang" },
  { negara: "Gabon", ibukota: "Libreville", level: "Sulit" },
  { negara: "Gambia", ibukota: "Banjul", level: "Sulit" },
  { negara: "Georgia", ibukota: "Tbilisi", level: "Sulit" },
  { negara: "Ghana", ibukota: "Accra", level: "Sulit" },
  { negara: "Grenada", ibukota: "Saint George's", level: "Sulit" },
  { negara: "Guatemala", ibukota: "Guatemala City", level: "Sedang" },
  { negara: "Guinea", ibukota: "Conakry", level: "Sulit" },
  { negara: "Guinea-Bissau", ibukota: "Bissau", level: "Sulit" },
  { negara: "Guinea Khatulistiwa", ibukota: "Malabo", level: "Sulit" },
  { negara: "Guyana", ibukota: "Georgetown", level: "Sulit" },
  { negara: "Haiti", ibukota: "Port-au-Prince", level: "Sulit" },
  { negara: "Honduras", ibukota: "Tegucigalpa", level: "Sedang" },
  { negara: "Hongaria", ibukota: "Budapest", level: "Sedang" },
  { negara: "India", ibukota: "New Delhi", level: "Mudah" },
  { negara: "Indonesia", ibukota: "Jakarta", level: "Mudah" },
  { negara: "Irak", ibukota: "Baghdad", level: "Sedang" },
  { negara: "Iran", ibukota: "Tehran", level: "Sedang" },
  { negara: "Irlandia", ibukota: "Dublin", level: "Sedang" },
  { negara: "Islandia", ibukota: "Reykjavik", level: "Sulit" },
  { negara: "Israel", ibukota: "Yerusalem", level: "Sedang" },
  { negara: "Italia", ibukota: "Roma", level: "Mudah" },
  { negara: "Jamaika", ibukota: "Kingston", level: "Sulit" },
  { negara: "Jepang", ibukota: "Tokyo", level: "Mudah" },
  { negara: "Jerman", ibukota: "Berlin", level: "Mudah" },
  { negara: "Kamboja", ibukota: "Phnom Penh", level: "Sulit" },
  { negara: "Kamerun", ibukota: "Yaoundé", level: "Sulit" },
  { negara: "Kanada", ibukota: "Ottawa", level: "Mudah" },
  { negara: "Kazakhstan", ibukota: "Nur-Sultan", level: "Sedang" },
  { negara: "Kenya", ibukota: "Nairobi", level: "Sulit" },
  { negara: "Kirgizstan", ibukota: "Bishkek", level: "Sulit" },
  { negara: "Kiribati", ibukota: "South Tarawa", level: "Sulit" },
  { negara: "Kolombia", ibukota: "Bogotá", level: "Sedang" },
  { negara: "Komoro", ibukota: "Moroni", level: "Sulit" },
  { negara: "Korea Selatan", ibukota: "Seoul", level: "Mudah" },
  { negara: "Korea Utara", ibukota: "Pyongyang", level: "Sulit" },
  { negara: "Kosta Rika", ibukota: "San José", level: "Sedang" },
  { negara: "Kroasia", ibukota: "Zagreb", level: "Sedang" },
  { negara: "Kuba", ibukota: "Havana", level: "Sulit" },
  { negara: "Kuwait", ibukota: "Kota Kuwait", level: "Sedang" },
  { negara: "Laos", ibukota: "Vientiane", level: "Sulit" },
  { negara: "Latvia", ibukota: "Riga", level: "Sedang" },
  { negara: "Lebanon", ibukota: "Beirut", level: "Sedang" },
  { negara: "Lesotho", ibukota: "Maseru", level: "Sulit" },
  { negara: "Liberia", ibukota: "Monrovia", level: "Sulit" },
  { negara: "Libya", ibukota: "Tripoli", level: "Sulit" },
  { negara: "Liechtenstein", ibukota: "Vaduz", level: "Sulit" },
  { negara: "Lituania", ibukota: "Vilnius", level: "Sedang" },
  { negara: "Luksemburg", ibukota: "Luksemburg", level: "Sedang" },
  { negara: "Madagaskar", ibukota: "Antananarivo", level: "Sulit" },
  { negara: "Maladewa", ibukota: "Malé", level: "Sulit" },
  { negara: "Malawi", ibukota: "Lilongwe", level: "Sulit" },
  { negara: "Malaysia", ibukota: "Kuala Lumpur", level: "Sedang" },
  { negara: "Mali", ibukota: "Bamako", level: "Sulit" },
  { negara: "Malta", ibukota: "Valletta", level: "Sulit" },
  { negara: "Maroko", ibukota: "Rabat", level: "Sedang" },
  { negara: "Marshall Islands", ibukota: "Majuro", level: "Sulit" },
  { negara: "Mauritania", ibukota: "Nouakchott", level: "Sulit" },
  { negara: "Mauritius", ibukota: "Port Louis", level: "Sulit" },
  { negara: "Meksiko", ibukota: "Mexico City", level: "Mudah" },
  { negara: "Mesir", ibukota: "Kairo", level: "Sedang" },
  { negara: "Mikronesia", ibukota: "Palikir", level: "Sulit" },
  { negara: "Moldova", ibukota: "Chișinău", level: "Sulit" },
  { negara: "Monako", ibukota: "Monako", level: "Sulit" },
  { negara: "Mongolia", ibukota: "Ulaanbaatar", level: "Sulit" },
  { negara: "Montenegro", ibukota: "Podgorica", level: "Sulit" },
  { negara: "Mozambik", ibukota: "Maputo", level: "Sulit" },
  { negara: "Myanmar", ibukota: "Naypyidaw", level: "Sulit" },
  { negara: "Namibia", ibukota: "Windhoek", level: "Sulit" },
  { negara: "Nauru", ibukota: "Yaren", level: "Sulit" },
  { negara: "Nepal", ibukota: "Kathmandu", level: "Sulit" },
  { negara: "Niger", ibukota: "Niamey", level: "Sulit" },
  { negara: "Nigeria", ibukota: "Abuja", level: "Sulit" },
  { negara: "Nikaragua", ibukota: "Managua", level: "Sedang" },
  { negara: "Norwegia", ibukota: "Oslo", level: "Sedang" },
  { negara: "Oman", ibukota: "Muscat", level: "Sedang" },
  { negara: "Pakistan", ibukota: "Islamabad", level: "Sedang" },
  { negara: "Palau", ibukota: "Ngerulmud", level: "Sulit" },
  { negara: "Panama", ibukota: "Panama City", level: "Sedang" },
  { negara: "Pantai Gading", ibukota: "Yamoussoukro", level: "Sulit" },
  { negara: "Papua Nugini", ibukota: "Port Moresby", level: "Sulit" },
  { negara: "Paraguay", ibukota: "Asunción", level: "Sulit" },
  { negara: "Peru", ibukota: "Lima", level: "Sedang" },
  { negara: "Polandia", ibukota: "Warsawa", level: "Sedang" },
  { negara: "Portugal", ibukota: "Lisbon", level: "Sedang" },
  { negara: "Prancis", ibukota: "Paris", level: "Mudah" },
  { negara: "Qatar", ibukota: "Doha", level: "Sedang" },
  { negara: "Republik Afrika Tengah", ibukota: "Bangui", level: "Sulit" },
  { negara: "Republik Ceko", ibukota: "Praha", level: "Sedang" },
  { negara: "Republik Demokratik Kongo", ibukota: "Kinshasa", level: "Sulit" },
  { negara: "Republik Dominika", ibukota: "Santo Domingo", level: "Sedang" },
  { negara: "Republik Kongo", ibukota: "Brazzaville", level: "Sulit" },
  { negara: "Rumania", ibukota: "Bucharest", level: "Sedang" },
  { negara: "Rusia", ibukota: "Moskwa", level: "Sedang" },
  { negara: "Rwanda", ibukota: "Kigali", level: "Sulit" },
  { negara: "Saint Kitts dan Nevis", ibukota: "Basseterre", level: "Sulit" },
  { negara: "Saint Lucia", ibukota: "Castries", level: "Sulit" },
  {
    negara: "Saint Vincent dan Grenadines",
    ibukota: "Kingstown",
    level: "Sulit",
  },
  { negara: "Samoa", ibukota: "Apia", level: "Sulit" },
  { negara: "San Marino", ibukota: "San Marino", level: "Sulit" },
  { negara: "Sao Tome dan Principe", ibukota: "São Tomé", level: "Sulit" },
  { negara: "Selandia Baru", ibukota: "Wellington", level: "Mudah" },
  { negara: "Senegal", ibukota: "Dakar", level: "Sulit" },
  { negara: "Serbia", ibukota: "Belgrade", level: "Sedang" },
  { negara: "Seychelles", ibukota: "Victoria", level: "Sulit" },
  { negara: "Sierra Leone", ibukota: "Freetown", level: "Sulit" },
  { negara: "Singapura", ibukota: "Singapura", level: "Mudah" },
  { negara: "Siprus", ibukota: "Nicosia", level: "Sulit" },
  { negara: "Slovakia", ibukota: "Bratislava", level: "Sedang" },
  { negara: "Slovenia", ibukota: "Ljubljana", level: "Sedang" },
  { negara: "Solomon Islands", ibukota: "Honiara", level: "Sulit" },
  { negara: "Somalia", ibukota: "Mogadishu", level: "Sulit" },
  { negara: "Spanyol", ibukota: "Madrid", level: "Sedang" },
  { negara: "Sri Lanka", ibukota: "Colombo", level: "Sulit" },
  { negara: "Sudan", ibukota: "Khartoum", level: "Sulit" },
  { negara: "Sudan Selatan", ibukota: "Juba", level: "Sulit" },
  { negara: "Suriah", ibukota: "Damaskus", level: "Sulit" },
  { negara: "Suriname", ibukota: "Paramaribo", level: "Sulit" },
  { negara: "Swedia", ibukota: "Stockholm", level: "Sedang" },
  { negara: "Swiss", ibukota: "Bern", level: "Sedang" },
  { negara: "Tajikistan", ibukota: "Dushanbe", level: "Sulit" },
  { negara: "Tanzania", ibukota: "Dodoma", level: "Sulit" },
  { negara: "Thailand", ibukota: "Bangkok", level: "Sedang" },
  { negara: "Timor Leste", ibukota: "Dili", level: "Sulit" },
  { negara: "Togo", ibukota: "Lomé", level: "Sulit" },
  { negara: "Tonga", ibukota: "Nukuʻalofa", level: "Sulit" },
  { negara: "Trinidad dan Tobago", ibukota: "Port of Spain", level: "Sulit" },
  { negara: "Tunisia", ibukota: "Tunis", level: "Sedang" },
  { negara: "Turki", ibukota: "Ankara", level: "Sedang" },
  { negara: "Turkmenistan", ibukota: "Ashgabat", level: "Sulit" },
  { negara: "Tuvalu", ibukota: "Funafuti", level: "Sulit" },
  { negara: "Uganda", ibukota: "Kampala", level: "Sulit" },
  { negara: "Ukraina", ibukota: "Kyiv", level: "Sedang" },
  { negara: "Uni Emirat Arab", ibukota: "Abu Dhabi", level: "Sedang" },
  { negara: "Uruguay", ibukota: "Montevideo", level: "Sulit" },
  { negara: "Uzbekistan", ibukota: "Tashkent", level: "Sulit" },
  { negara: "Vatikan", ibukota: "Vatikan", level: "Sulit" },
  { negara: "Venezuela", ibukota: "Caracas", level: "Sedang" },
  { negara: "Vietnam", ibukota: "Hanoi", level: "Sedang" },
  { negara: "Yaman", ibukota: "Sana'a", level: "Sulit" },
  { negara: "Yordania", ibukota: "Amman", level: "Sedang" },
  { negara: "Yunani", ibukota: "Athena", level: "Sedang" },
  { negara: "Zambia", ibukota: "Lusaka", level: "Sulit" },
  { negara: "Zimbabwe", ibukota: "Harare", level: "Sulit" },
];
